### ISSUE TITLE
AttributeError: 'str' object has no attribute 'n' with encrypt function implentation

### ISSUE THREAD

**Issue by DRISHTANT-DUBEY** [sybrenstuvel/python-rsa#214]
I have been trying to peruse my implentation error im parameters to the encrypt function of your package and seems like the problem wis the way i am passing my public key to the function as params 
Error is mentioned in second paragraph

```python
def encrypt(message, key):
    return rsa.encrypt(message.encode('ascii'), key)

publicKey, privateKey = loadKeys()
ciphertext = encrypt(orignal, publicKey)
signature = sign(orignal, privateKey)
text = decrypt(ciphertext, privateKey)

File "C:\Users\dubdri01\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rsa\pkcs1.py", line 194, in encrypt
    keylength = common.byte_size(pub_key.n)
AttributeError: 'str' object has no attribute 'n'
```

pls help me out to navigate this error

**Comment by myheroyuki** [comment]
The error suggests you're passing in the wrong type to `rsa.encrypt` for the `key` argument. It should be type `rsa.key.PublicKey`. It's hard to diagnose anything else since you've omitted the code for `loadKeys`. Please see [the documentation](https://stuvel.eu/python-rsa-doc/usage.html) for correct usage. That has everything you need!

**Comment by sybrenstuvel** [comment]
Thanks @myheroyuki for helping out. I'll assume that the issue has been resolved.
